### ISSUE TITLE
Request for more info about the 3D engine RTL design

### ISSUE THREAD

**Issue by ma-exposito-gd** [Kenji-Ishimaru/polyphony#1]
I would love to see in the documentation how many Logic Elements the 3D engine and LCD controller cores take on the XC7Z020.

In addition to that, it would be very interesting to have a ballpark estimate of how many triangles per second the system is able to render in the Zed Board (flat and textured).

This is a very interesting project.
Thank you very much in advance.

**Comment by Kenji-Ishimaru** [comment]
The LUT usage of the system is about 27%.

1. Slice Logic (7z020clg484-1)
--------------

+----------------------------+-------+-------+-----------+-------+
|          Site Type         |  Used | Fixed | Available | Util% |
+----------------------------+-------+-------+-----------+-------+
| Slice LUTs                 | 14303 |     0 |     53200 | 26.89 |
|   LUT as Logic             | 13689 |     0 |     53200 | 25.73 |
|   LUT as Memory            |   614 |     0 |     17400 |  3.53 |
|     LUT as Distributed RAM |   286 |     0 |           |       |
|     LUT as Shift Register  |   328 |     0 |           |       |
| Slice Registers            | 14682 |     0 |    106400 | 13.80 |
|   Register as Flip Flop    | 14682 |     0 |    106400 | 13.80 |
|   Register as Latch        |     0 |     0 |    106400 |  0.00 |
| F7 Muxes                   |   117 |     0 |     26600 |  0.44 |
| F8 Muxes                   |     9 |     0 |     13300 |  0.07 |
+----------------------------+-------+-------+-----------+-------+

The rendering performance is VERY slow, especially with texture mapping.
ex) 3000 small triangles/s(30fps) without texture mapping.

The main reasons for low performance are:
- Focused on less LUT consumption rather than rendering performance.
- All AXI masters (CPU, Fragment R/W, Texture, LCD,... ) share a single DDR.
- Simple horizontal rasterization, tile-based rasterization is not used.
- Fragment pipeline sends parameters one by one, not in parallel.
